id: P2BD1DFD4
initial_creation_type: input
source_metadata:
  title: Vajracchedikā Prajñāpāramitā
  language: zh
  volumes:
    2fd33e931d654b0daca999ba6762c8a9:
      title: CIII_a
      base_file: CIII_a.txt
      work_id: WFD73A26C
    f2a94829826841948906cf50f5477405:
      title: CIII_b
      base_file: CIII_b.txt
      work_id: W78DA704C
    356a2efc8a374411a589f04e38c4db22:
      title: CIII_c
      base_file: CIII_c.txt
      work_id: W81BAFEE1
    ab4c4b0c772f476089bc531326173354:
      title: CIII_d
      base_file: CIII_d.txt
      work_id: WFFB54232
    22a646584e0140f5a485dabe09bdeb7e:
      title: CIII_e
      base_file: CIII_e.txt
      work_id: WD4F0F4BA
    083af235172949e28da5cedc027d702b:
      title: CII_a
      base_file: CII_a.txt
      work_id: W2836248B
    542ddbb324a349b384e352d01864b438:
      title: CII_b
      base_file: CII_b.txt
      work_id: W311966D6
    cae09e6eed7944c5bfcc6d8c3d89b9ce:
      title: CII_c
      base_file: CII_c.txt
      work_id: W75C833A9
    780ac355d97645d491ae53449cc34fc0:
      title: CIV_a
      base_file: CIV_a.txt
      work_id: WFB89545B
    805daddd3dcb4a59802d427689d130c4:
      title: CIV_b
      base_file: CIV_b.txt
      work_id: WB6419A7D
    89ef80bf2c634a49b476e957192e821c:
      title: CIV_c
      base_file: CIV_c.txt
      work_id: W2DFDDB04
    6eee2f1ee39c40339f98280dafee67d6:
      title: CIV_d
      base_file: CIV_d.txt
      work_id: W4B56BF1B
    3abd96b5dc8b470c8758f5a0cf24aece:
      title: CIV_e
      base_file: CIV_e.txt
      work_id: W4FADADCA
    d72e3a1e8eac44589ddb11a636cf9970:
      title: CIV_f
      base_file: CIV_f.txt
      work_id: W1FE491AC
    57bc6c118638409aaa1ed48926f74e84:
      title: CIV_g
      base_file: CIV_g.txt
      work_id: WE4B12C98
    945aa48311e54ccd877d0b3b19766631:
      title: CIV_h
      base_file: CIV_h.txt
      work_id: WD2BDB04D
    d581102797404cdda15917acbf80aa99:
      title: CIX_a
      base_file: CIX_a.txt
      work_id: WDFFD5D02
    53071005a52645408fe7ddb75fcef197:
      title: CIX_b
      base_file: CIX_b.txt
      work_id: WAF25BA35
    80de57b4b5e04035a81410a7e2620af6:
      title: CI_a
      base_file: CI_a.txt
      work_id: W83E04F3F
    c9cf40a1f0264ed48249b8f59651f8e7:
      title: CI_b
      base_file: CI_b.txt
      work_id: W18311F85
    713a06700ea846468a7e15d6d32cb116:
      title: CI_c
      base_file: CI_c.txt
      work_id: W0D2D0029
    1a32e38a5bb64c12840a1a2384eaf31e:
      title: CI_d
      base_file: CI_d.txt
      work_id: W0FC26C76
    1c0be12dc0184b22be26f7b8b9630fe5:
      title: CI_e
      base_file: CI_e.txt
      work_id: W9589FB9E
    fff1ceae289d44b5b448bded0ecafcd4:
      title: CVIII_a
      base_file: CVIII_a.txt
      work_id: W50900213
    f55821896032405d81e91d462cd74038:
      title: CVIII_b
      base_file: CVIII_b.txt
      work_id: W456EBCE4
    df79ffbef35c4847bdcb21febbd3f10a:
      title: CVII_a
      base_file: CVII_a.txt
      work_id: W045E6B42
    f3dcce733d244bc9bd8caef22ae5f2e6:
      title: CVII_b
      base_file: CVII_b.txt
      work_id: W54F24234
    00c41eeeccdc416c852e8a04bb7b2f6e:
      title: CVII_c
      base_file: CVII_c.txt
      work_id: W8FB30230
    e3b0fdd1dd3f4a33a6b5554739a8a1c9:
      title: CVII_d
      base_file: CVII_d.txt
      work_id: W6E1B62B0
    970acef9f5494735977cca448d569e0a:
      title: CVII_e
      base_file: CVII_e.txt
      work_id: W9D8F769D
    4f1824c371a14a11b8af68555645ff1e:
      title: CVII_f
      base_file: CVII_f.txt
      work_id: W1FAEDE91
    55c69b6f36e944769bc906fea4eed88a:
      title: CVII_g
      base_file: CVII_g.txt
      work_id: W4CBECAC7
    4791f83028d84557879643127f59a02f:
      title: CVII_h
      base_file: CVII_h.txt
      work_id: W38AB8AE9
    2c456e12084b4fce81e6835737d0b35c:
      title: CVI_a
      base_file: CVI_a.txt
      work_id: WA7CCCD77
    31cd48054ec54a4995c57dc186ca2bd8:
      title: CVI_b
      base_file: CVI_b.txt
      work_id: W9C0CC001
    09ad3c4fe70846b7994610f7b6d3e962:
      title: CVI_c
      base_file: CVI_c.txt
      work_id: W145D16C5
    5916a202c3ff41f09adb1ec3405eda24:
      title: CV_a
      base_file: CV_a.txt
      work_id: WD90FE8DB
    494e7eff454a4955935e9e3a31a47360:
      title: CV_b
      base_file: CV_b.txt
      work_id: WFE555F85
    20d70d5854454b5e894255e1e9654866:
      title: CV_c
      base_file: CV_c.txt
      work_id: WAC8234AA
    0d956295c1b8445a91fe5e77a87378f1:
      title: CXIII_a
      base_file: CXIII_a.txt
      work_id: W10A41A5E
    2a99d0e6565a441192c0329b23878a3a:
      title: CXIII_b
      base_file: CXIII_b.txt
      work_id: W66133622
    8439a42d67274dedab0ab3e0d0245071:
      title: CXII_a
      base_file: CXII_a.txt
      work_id: WCF26442E
    e596f43f575d437aa2654bb4389ae7d8:
      title: CXII_b
      base_file: CXII_b.txt
      work_id: W044890E8
    a31ef8a2e7a24e15928ecd871393e29b:
      title: CXIV_a
      base_file: CXIV_a.txt
      work_id: WF224407A
    517cef1daf7c4516aa4454099a65a39d:
      title: CXIV_b
      base_file: CXIV_b.txt
      work_id: WC1A4FF47
    10fbcc6dfff9411bbf0b68b1cea9d008:
      title: CXI_a
      base_file: CXI_a.txt
      work_id: WA142113A
    ecd0d58502084ce3b1df89a9a84e73fe:
      title: CXV_a
      base_file: CXV_a.txt
      work_id: W05CD1B65
    a9c7eb8b981f426b9c140a831b407a85:
      title: CXV_b
      base_file: CXV_b.txt
      work_id: W77E71CD8
    60e490e19a9449fd825708163c2c808a:
      title: CX_a
      base_file: CX_a.txt
      work_id: W8E2FB0EB
    3555ab844d734281be9d8994a4ebb452:
      title: CX_b
      base_file: CX_b.txt
      work_id: WCADD504A
    1d1447a04cca4a3781e38c1ab1dca40a:
      title: Colophon
      base_file: Colophon.txt
      work_id: W4ECFD466
    241efaf68e4940faba88c0622aef9dd5:
      title: Preface
      base_file: Preface.txt
      work_id: W04595E56
    335fe8d21dd24b9f846d06c36f1bc681:
      title: Title
      base_file: Title.txt
      work_id: W0C4AB7F4
    7275496216184373bd65f88e01246d4d:
      title: §1
      base_file: §1.txt
      work_id: W070B1D54
    7dfa49eb896c46a7b2c446eb52549021:
      title: §11
      base_file: §11.txt
      work_id: W43B6D2D2
    6c05b815c5b7482b86495c4c0bbbc042:
      title: §12
      base_file: §12.txt
      work_id: W6CAB414A
    6cf4bd212e7d4a1e833db9a69aad4189:
      title: §2
      base_file: §2.txt
      work_id: W4588AE4B
    59836251d9e34defbaa404e65074a646:
      title: §23
      base_file: §23.txt
      work_id: W713090BE
    a93f361d7263467cb32fa1c353f7773c:
      title: §24
      base_file: §24.txt
      work_id: W049DFF14
    8b76e25cc8e643159f2160fa872ef5d5:
      title: §25
      base_file: §25.txt
      work_id: WEF3CBAF9
    361a55d79b1e436cbb07d3347d0e38b4:
      title: §27
      base_file: §27.txt
      work_id: W54832564
    6d4912690f9c4ec98c4d805602c33ae9:
      title: §28
      base_file: §28.txt
      work_id: W0093D15F
    263d0dd1b4a14642a631986bd8df24d0:
      title: §29
      base_file: §29.txt
      work_id: W9B400DF2
    0ccf815ce4864a5b92e220fb95c4dec5:
      title: §3
      base_file: §3.txt
      work_id: W77478ED9
    7283a652c803495cbb68ef367c1847d7:
      title: §4
      base_file: §4.txt
      work_id: WD975F40F
    aa15608274ab49ce9109d3acd3324fa2:
      title: §5
      base_file: §5.txt
      work_id: WA4240EC5
    dd6a8a02b8c6492cb6353a6cefed741c:
      title: §6
      base_file: §6.txt
      work_id: W7CFDA29E
    09864170ec754101994bd39e6012685b:
      title: §7
      base_file: §7.txt
      work_id: W7775432C
    6e55310fa2b14cdd8c8713ec6469a13e:
      title: §8
      base_file: §8.txt
      work_id: W969387BB
  chapter_to_tile:
    CI: §9
    CII: §10
    CIII: §13
    CIV: §14
    CV: §15
    CVI: §16
    CVII: §17
    CVIII: §18
    CIX: §19
    CX: §21
    CXI: §22
    CXII: §26
    CXIII: §30
    CXIV: §31
    CXV: §32
created_at: '2022-03-01T21:54:38.191317'
last_modified_at: '2022-03-01T21:54:38.191351'
